services:

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=int311
      - SUBDOMAINS=wildcard
      - VALIDATION=http
      - SWAG_AUTORELOAD=true
      - DOCKER_MODS=linuxserver/mods:swag-dashboard
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./swag/config:/config
    
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./bookmarks:/bookmarks
      - ./firefox/preferences:/usr/lib/firefox/browser/defaults/preferences/
      - ./data:/data
      - ./firefox/policies.json:/etc/firefox/policies/policies.json
    shm_size: "1gb"
    restart: unless-stopped

  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - INSTALL_PACKAGES=fonts-noto-cjk
      - LC_ALL=ru_RU
    volumes:
      - ./chromium/bookmarks:/config/.config/chromium/Default/Bookmarks
      - ./data:/data
    shm_size: "1gb"
    restart: unless-stopped

  tor:
    image: paradoxxs/tor-desktop
    container_name: tor
    volumes:
      - ./bookmarks:/bookmarks
      - ./tor/preferences:/tor/tor-browser/Browser/browser/defaults/preferences/
      - ./data:/data
    shm_size: "1gb"
    restart: unless-stopped

  telegram:
    image: paradoxxs/telegram
    container_name: telegram
    volumes:
      - ./data:/data
    restart: unless-stopped

  keybase:
    image: paradoxxs/keybase
    container_name: keybase
    shm_size: "1gb"
    volumes:
      - ./data:/data
    restart: unless-stopped

  remote-desk:
    image: lscr.io/linuxserver/rdesktop:debian-kde
    container_name: remote-desktop
    ports:
      - "4005:3389"
    volumes:
      - ./data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow     
      - INSTALL_PACKAGES=fonts-noto-cjk
      - LC_ALL=ru_RU
    restart: unless-stopped