services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: ${CASE_NUMBER}_firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./bookmarks:/bookmarks
      - ./${CASE_NUMBER}/firefox/preferences:/usr/lib/firefox/browser/defaults/preferences/
    ports:
      - "3000:3000"
      - "3001:3001"
    shm_size: "1gb"
    restart: unless-stopped

  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: ${CASE_NUMBER}_chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./chromium/bookmarks:/config/.config/chromium/Default/Bookmarks
    ports:
      - "4000:3000"
      - "4001:3001"
    shm_size: "1gb"
    restart: unless-stopped

  tor:
    image: paradoxxs/tor-desktop
    container_name: ${CASE_NUMBER}_tor
    volumes:
      - ./bookmarks:/bookmarks
      - ./${CASE_NUMBER}/tor/preferences:/tor/tor-browser/Browser/browser/defaults/preferences/
    ports:
      - "5000:3000"
    shm_size: "1gb"
    restart: unless-stopped

    telegram:
      image: paradoxxs/telegram
      container_name: ${CASE_NUMBER}_telegram
      ports:
        - "6000:3000"
      shm_size: "1gb"
      restart: unless-stopped

    keybase:
      image: paradoxxs/keybase
      container_name: ${CASE_NUMBER}_keybase
      ports:
        - "7000:3000"
      shm_size: "1gb"
      restart: unless-stopped