services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./bookmarks:/bookmarks
      - ./firefox/preferences:/usr/lib/firefox/browser/defaults/preferences/
    ports:
      - "4000:3000"
    shm_size: "1gb"
    restart: unless-stopped

  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - INSTALL_PACKAGES=fonts-noto-cjk
      - LC_ALL=ru_RU
    volumes:
      - ./chromium/bookmarks:/config/.config/chromium/Default/Bookmarks
    ports:
      - "4001:3000"
    shm_size: "1gb"
    restart: unless-stopped

  tor:
    image: paradoxxs/tor-desktop
    container_name: tor
    volumes:
      - ./bookmarks:/bookmarks
      - ./tor/preferences:/tor/tor-browser/Browser/browser/defaults/preferences/
    ports:
      - "4002:3000"
    shm_size: "1gb"
    restart: unless-stopped

  telegram:
    image: paradoxxs/telegram
    container_name: telegram
    ports:
      - "4003:3000"
    restart: unless-stopped

  keybase:
    image: paradoxxs/keybase
    container_name: keybase
    ports:
      - "4004:3000"
    shm_size: "1gb"
    restart: unless-stopped

  remote-desk:
    image: lscr.io/linuxserver/rdesktop:debian-kde
    container_name: remote-desktop
    ports:
      - "4005:3389"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow     
      - INSTALL_PACKAGES=fonts-noto-cjk
      - LC_ALL=ru_RU
    restart: unless-stopped